var superHeroes = [];
superHeroes.push('Ironman');
superHeroes.push('Superman');
superHeroes.push('Ganduman');
var users = [];
users.push({ id: 1, name: 'hello', isLoggedIn: true });
users.push({ id: 2, name: 'world', isLoggedIn: false });
// console.log(users);
var mdArray = [];
mdArray.push([]);
mdArray[0].push(1);
mdArray.push([]);
mdArray[1].push(2);
console.log(mdArray);
